version: '3.8'

services:
  app:
    build: .
    container_name: bee-garden
    volumes:
      - .:/app
      - /app/node_modules  # Don't overwrite node_modules from host
    ports:
      - "8081:8081"
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - REACT_NATIVE_PACKAGER_HOSTNAME=host.docker.internal
    stdin_open: true
    tty: true
